// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4wBmBf4Jx0RL5CricCM-_bAjBdCCkOx0',
    appId: '1:81840245229:web:639ae43ffa85b662deffe4',
    messagingSenderId: '81840245229',
    projectId: 'tuitionmedia-af0bf',
    authDomain: 'tuitionmedia-af0bf.firebaseapp.com',
    storageBucket: 'tuitionmedia-af0bf.appspot.com',
    measurementId: 'G-BF6WSW9Z27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7ijwIvOZ7NttmGrQ3pdhHZhIHWAv2sw',
    appId: '1:81840245229:android:9e0acc7970fedc13deffe4',
    messagingSenderId: '81840245229',
    projectId: 'tuitionmedia-af0bf',
    storageBucket: 'tuitionmedia-af0bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSO8IwdfS1jPNzIm03S3RCXXoi3a_xPQ0',
    appId: '1:81840245229:ios:1b3b387df1a86ccbdeffe4',
    messagingSenderId: '81840245229',
    projectId: 'tuitionmedia-af0bf',
    storageBucket: 'tuitionmedia-af0bf.appspot.com',
    iosBundleId: 'com.example.tuitionMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSO8IwdfS1jPNzIm03S3RCXXoi3a_xPQ0',
    appId: '1:81840245229:ios:1b3b387df1a86ccbdeffe4',
    messagingSenderId: '81840245229',
    projectId: 'tuitionmedia-af0bf',
    storageBucket: 'tuitionmedia-af0bf.appspot.com',
    iosBundleId: 'com.example.tuitionMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4wBmBf4Jx0RL5CricCM-_bAjBdCCkOx0',
    appId: '1:81840245229:web:66cc1ae32c4ee947deffe4',
    messagingSenderId: '81840245229',
    projectId: 'tuitionmedia-af0bf',
    authDomain: 'tuitionmedia-af0bf.firebaseapp.com',
    storageBucket: 'tuitionmedia-af0bf.appspot.com',
    measurementId: 'G-7BF3GSXHLN',
  );
}
